### ISSUE TITLE
Swift library throws "IOI2CInterfaceOpen failed"

### ISSUE THREAD

**Issue by xzhih** [aleksey-mashanov/swift-ddc#2]
Hi there.

I try to use your library in my own project, but it throws an error, "IOI2CInterfaceOpen failed"

Then I build the command line tool binary file and it works fine.

my code here 

```swift 
var iterator = io_iterator_t()
guard IOServiceGetMatchingServices(kIOMasterPortDefault, IOServiceMatching("AppleDisplay"), &iterator) == kIOReturnSuccess else {
    return
}
defer { IOObjectRelease(iterator) }
while case let service = IOIteratorNext(iterator), service != 0 {
    do {
        let sem = DispatchSemaphore(value: 0)
        let ddc = try DDC(display: service)
        ddc.getVCPFeature(.brightness) {
            switch $0 {
            case .success(let reply):
                print("Brightness: \(reply.present)%")
            case .failure(let error):
                print("Failed to get brightness: \(String(describing: error))")
            }
            sem.signal()
        }
        sem.wait()
    } catch {
        print("try error")
    }
    IOObjectRelease(service)
}
```

**Comment by aleksey-mashanov** [comment]
I can recommend you to wrap `sem.wait()` with `withExtendedLifetime(ddc) { }` block to ensure connection is still open while get-vcp-feature async request is in progress. Though this should not be the reason of the issue. Unfortunately, I have no access to an external display to debug your code right now, it looks good.

**Comment by xzhih** [comment]
I closed the sandbox then it work, thanks
